site_name: Cahiers Seyès
site_url: https://ligne.github.io/cahiers/
repo_url: https://github.com/ligne/cahiers/
edit_uri: edit/main/docs/
theme:
  name: material
  favicon: img/favicon.ico
  features:
    - content.action.edit
    - toc.integrate  # not compatible with section index pages (navigation.indexes)
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
plugins:
  - search
  - awesome-nav
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: timeago
      enable_creation_date: true
      timezone: Europe/London
